# Generated by Django 2.2.10 on 2020-05-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0004_auto_20200508_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='tags',
            field=models.ManyToManyField(to='bookmark.Tag'),
        ),
    ]
