# Generated by Django 2.2.10 on 2020-05-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0006_auto_20200508_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='image',
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='tags',
            field=models.ManyToManyField(to='bookmark.Tag'),
        ),
    ]
