# Generated by Django 2.2.10 on 2020-05-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0008_auto_20200509_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarkform',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='描述'),
        ),
    ]
