# Generated by Django 2.2.10 on 2020-05-10 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0009_auto_20200510_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmarkform',
            old_name='category_name',
            new_name='folder_name',
        ),
    ]
