# Generated by Django 2.2.10 on 2020-05-10 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0010_auto_20200510_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='category',
            new_name='folder',
        ),
    ]
